services:
  postgres:
    container_name: "postgres"
    image: "postgres:18.2"
    restart: always
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: migration_user
      POSTGRES_PASSWORD: migrate
      POSTGRES_DB: migrated
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U migration_user -d migrated"]
      interval: 5s
      timeout: 5s
      retries: 3
    volumes:
      - postgres_data:/var/lib/postgresql

  migr8:
    depends_on:
      postgres:
        condition: service_healthy
    container_name: "migr8"
    restart: always
    build:
      context: ..
      dockerfile: build/package/Dockerfile
    environment:
      M8_MIG_DIR: migrations
      M8_DSN: "postgres://migration_user:migrate@postgres:5432/migrated?sslmode=disable"
    command: ["up"]
    ports:
      - "8080:8080"

volumes:
  postgres_data:
