version: "2"

run:
  build-tags:
    - integration
  tests: true

linters:
  settings:
    funlen:
      lines: 150
      statements: 80
    godox:
      keywords:
        - TODO
        - BUG
        - FIXME
    depguard:
      rules:
        main:
          allow:
            - $gostd
            - github.com/Lamerkid/migr8
            - github.com/jackc/pgx/v5/stdlib
            - github.com/DATA-DOG/go-sqlmock
            - github.com/stretchr/testify/require
            - github.com/stretchr/testify/assert
        test:
          allow:
            - $gostd
            - github.com/Lamerkid/migr8
            - github.com/jackc/pgx/v5/stdlib
            - github.com/DATA-DOG/go-sqlmock
            - github.com/stretchr/testify/require
            - github.com/stretchr/testify/assert

  default: none

  enable:
    - asciicheck
    - bodyclose
    - depguard
    - dogsled
    - dupl
    - durationcheck
    - errorlint
    - exhaustive
    - copyloopvar
    - funlen
    - gocognit
    - goconst
    - gocritic
    - gocyclo
    - godot
    - goheader
    - gomoddirectives
    - gomodguard
    - goprintffuncname
    - gosec
    - govet
    - importas
    - ineffassign
    - lll
    - makezero
    - misspell
    - nestif
    - nilerr
    - noctx
    - nolintlint
    - prealloc
    - predeclared
    - revive
    - rowserrcheck
    - sqlclosecheck
    - staticcheck
    - tagliatelle
    - thelper
    - tparallel
    - unconvert
    - unparam
    - unused
    - wastedassign
    - whitespace
    - godox

formatters:
  enable:
    - gci
    - gofmt
    - gofumpt
