name: CI tests

on: [push, pull_request]

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v6
      - uses: actions/setup-go@v6
        with:
          go-version: "1.25"

      - name: Lint
        uses: golangci/golangci-lint-action@v9
        with:
          version: v2.10.1

  unit-tests:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v6
      - uses: actions/setup-go@v6
        with:
          go-version: "1.25"

      - name: Run unit tests
        run: go test -race -count=100 -timeout=1m ./...

  integration-tests:
    runs-on: ubuntu-latest
    services:
      postgres:
        image: postgres:18.2
        env:
          POSTGRES_USER: postgres
          POSTGRES_PASSWORD: postgres
          POSTGRES_DB: migr8_test
        options: >-
          --health-cmd pg_isready
          --health-interval 5s
          --health-timeout 5s
          --health-retries 3
        ports:
          - 5432:5432
    steps:
      - uses: actions/checkout@v6
      - uses: actions/setup-go@v6
        with:
          go-version: "1.25"
      - name: Run integration tests
        run: go test -v -tags=integration ./test/integration/...
        env:
          M8_DSN: postgres://postgres:postgres@localhost:5432/migr8_test?sslmode=disable
          M8_DIR: ./

  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v6
      - uses: actions/setup-go@v6
        with:
          go-version: "1.25"

      - name: Build
        env:
          GOOS: linux
          GOARCH: amd64
        run: go build -v ./cmd/migr8
